# Generated by Django 2.2.2 on 2019-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_content', models.CharField(default='未完成', max_length=3)),
            ],
            options={
                'db_table': 'mission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
                ('u_num', models.CharField(default='', max_length=20)),
                ('u_password', models.CharField(max_length=255)),
                ('u_ticket', models.CharField(max_length=255, null=True)),
                ('u_tel', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
