# Generated by Django 2.2.2 on 2019-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('side_mission', '0002_auto_20190613_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mis_contact',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='mission',
            name='mis_title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
